version: "3.9"
services:
  reactapp:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: controla-react
    ports:
      - 80:3000
    build: .
    volumes:
      - /app/node_modules
      - ./reactapp:/app
